### ISSUE TITLE
The ability to create a TQL Query Piechart showcasing a group of tagged projects over time.

### ISSUE THREAD

**Issue by dotMavriQ** [mcndt/obsidian-toggl-integration#110]
As stated. 

I typically categorize the work I do in three separate categories on Toggl. 

I did this with this plugin in mind, as my dream would be to be able to see how much work I do, on a monthly basis, with every category of work that I do. 

I would LOVE for this to be implemented!

**Comment by mcndt** [comment]
Can you explain in more detail what you mean?

**Comment by dotMavriQ** [comment]
Yes I can! 

So let's say that logged projects using tags 1,2,3. 

How would one go about to showcase only 1 and 2 in a piechart. 

I know EXCLUDE works but that's only per project, no?

**Comment by mcndt** [comment]
So if I understand correctly, you want a pie chart where each segment represents a tag rather than a project?

**Comment by dotMavriQ** [comment]
Ideally I would want to be able to exclude all projects that have a specific tag.

**Comment by mcndt** [comment]
AFAIK only time entries can have tags in Toggl, not projects directly. The Toggl API only allows to filter by tag on time entries, so it's definitely not straight-forward to filter projects by occurence of a time entry with a tag within the queried time frame.

Since Toggl doesn't support it, I'm afraid the plugin can't either.
