### ISSUE TITLE
[[Issue]] : infinite loading's query 

### ISSUE THREAD

**Issue by joniac1** [mcndt/obsidian-toggl-integration#114]
Hi, thanks for this great plugin

I have an issue, the query does not show de chart because it loads infinitely. 

Has anyone a solution ? 

Joniac

**Comment by rogden-pe** [comment]
This is also an issue for me. It renders the integration practically unusable

**Comment by mcndt** [comment]
How big is the timespan over which you are querying? 

The Toggl API can be very slow with large intervals (e.g. 6 months, 1 year), there's not much I can do about it unfortunately.

If you find that the entire plugin gets stuck loading (because you queued too many large queries), you can try running the Obsidian command "Reload app without saving". That should restart the plugin as well and reset the queue.

**Comment by mcndt** [comment]
Closing this for now, assuming it is related to the slow API. #91 might fix it (if the v9 API from Toggl is any better)

**Comment by mcndt** [comment]
Migration to new toggl API is finished in release 0.10.0. Loading summary reports should be much faster now!

https://github.com/mcndt/obsidian-toggl-integration/releases/tag/0.10.0
