### ISSUE TITLE
Exclude Tags not filtering out time entries

### ISSUE THREAD

**Issue by dljsjr** [mcndt/obsidian-toggl-integration#129]
I'm using Toggl Track to track where my time is spent at my desk job, and one of the things I would like to be able to do is visualize, comparatively, my planned work vs interrupt based work via tags.

`INCLUDE TAGS` seems to be working; if I `INCLUDE TAGS #unplanned` then I only get tagged entries. But if I use `EXCLUDE TAGS #unplanned` on another query, it doesn't actually exclude those entries.

The real life, not redacted query from my Vault is actually pretty straight forward:

	```toggl
	SUMMARY
	WEEK
	INCLUDE CLIENTS "Work"
	EXCLUDE TAGS #unplanned
	TITLE "Planned Work"
	```

Thanks for the awesome plugin!

EDIT: Screenshot
![image](https://user-images.githubusercontent.com/444635/234722218-971cd323-eee6-4b52-822a-9f02746cc83f.png)

**Comment by mayukhc** [comment]
Same issue, include working whereas exclude not working for both projects and tags. Love the plugin, hope there's a fix.

**Comment by mcndt** [comment]
I think I see the problem in the code, will have a look.

**Comment by mcndt** [comment]
Turns out the Toggl API only supports including tags and not excluding tags. For the list view I am able to work around this by filtering the results locally, but for the summary report the API only returns me the totals per project and per day, so I can only filter by included tags here.

I will make the plugin throw a parsing error when generating summary reports with excluded tags in the upcoming 0.11.0 release.

**Comment by mayukhc** [comment]
Ok, what about excluding projects in summary views ?  Below query is working in list view, not in summary. The plugin version is 0.10.0.
```toggl
SUMMARY
FROM 2023-07-14 TO TODAY
EXCLUDE PROJECTS "Waste", "Routine"
SORT DESC
```

**Comment by mcndt** [comment]
It should be possible, can you make a new issue for this?
