### ISSUE TITLE
Bug: Momentarily unable to type in Obsidian workspace after starting previously used timer with keyboard shortcut

### ISSUE THREAD

**Issue by AetheresMMI** [mcndt/obsidian-toggl-integration#18]
## The Issue
Whenever I start a previously used timer with a keyboard shortcut (in my case, CMD + T), I am frequently unable to enter text in my primary workspace afterwards. For some reason, it usually takes a few seconds for this bug to show up--I am typically able to type for a few seconds, and only later am I unable to enter text. It is still possible to enter text in areas like the search bar, command palette, and quick switcher. As soon as I move my cursor out of my workspace and back in, the issue resolves itself. While this may not be directly related to the Toggl integration plugin, I have not had this issue until using the plugin, and it only comes up after triggering a timer.
## Steps to Reproduce
1. Start a previously used timer by using a keyboard shortcut
2. Attempt to enter text into workspace (bug may not show up immediately)

**Comment by mcndt** [comment]
Interesting bug report. I feel like your description sounds familiar to me, although in my case I encountered it seemingly randomly and since long before I created the plugin. 

I tried your steps to reproduce on both my desktop and laptop but I cannot reproduce it. Do you have this same bug with other search modals, such as the file switcher or the command palette? Afaik they are built on the same UI component as the 'new timer' flow.

**Comment by mcndt** [comment]
I'll keep your thread open for now to see if more people report this issue.

**Comment by mcndt** [comment]
Closing this thread due to inactivity. Don’t hesitate to comment if you still encounter this problem.
