### ISSUE TITLE
Description of item in list reports overflows obsidian page width when longer than 2 lines

### ISSUE THREAD

**Issue by aventuraviper** [mcndt/obsidian-toggl-integration#43]
I have some very long Toggl entries due to tracking Todoist Tasks that are themselves generated using the Todoist Outlook add-on.

When these are pulled into a list style report by this obsidian plugin, they overflow the space given and produce a horizontal scroll bar (see attached image).

The task duration is also pushed off. 

I think there should be some sort of max length before an item is trimmed to prevent this if possible.

![image](https://user-images.githubusercontent.com/23149353/148909366-ec69e857-248e-4e5c-b512-fe4b82ee0377.png)

**Comment by mcndt** [comment]
Hey thanks for letting me know about this problem! A few points:

1. Of course this overflow is unintentional. I will look into fixing that either by trimming the description or by letting it continue on additional lines before it pushes out the task duration.

2. I notice your task description is a markdown-style link. Should this be parsed so that the list only shows the link's description and not the URL?

PS: I edited your original comment to blur the URL just out of caution if it contained any sensitive information.

**Comment by aventuraviper** [comment]
Awesome, thank you!

In regards to 2) yes, if possible that would be ideal (and help negate the issue in the first place).

Thanks for editing, I should have done that myself!

**Comment by mcndt** [comment]
It looks like the production version of the plugin already wraps descriptions correctly. I think the issue was that your description contained a very long link without spaces, and CSS only breaks at whitespace characters by default. Either way I'll ensure it doesn't overflow

**Comment by mcndt** [comment]
Merged fixes for both issues to master, will be available in release 0.5.1 soon.

**Comment by aventuraviper** [comment]
Amazing - reports look great again!

Thank you for such a swift fix
