### ISSUE TITLE
sorting feature?

### ISSUE THREAD

**Issue by mmfs37** [mcndt/obsidian-toggl-integration#80]
I am new so there is probably already that feature.
![image](https://user-images.githubusercontent.com/100991030/161832654-400f540d-fe55-4b66-b076-ecc9687b4a06.png)
I currently have the problem that my daily data is not ordered by time. I would greatly appreciate it, if the datasets are ordered by their amount. So the highest percentage points at the top and the lowest at the bottom.

IF THIS IS ALREADY POSSIBLE:
please tell me how to do that. I would greatly appreciate any help
a simple sort desc doesn't work

IF THIS IS NOT A FEATURE YET:
please add it as a feature it would immensely improve it. 
Seeing what I did today the most amount of time is the reason I use toggl Tracker so if that would be easier with a sorting feature, i think the programming effort would be worth it for everybody.

**Comment by mcndt** [comment]
Hi @mmfs37,

I'm confused because `SORT ASC` and `SORT DESC` should work on project summaries:

Example:

````
```toggl
summary week
sort desc
title "This week (all)"
```
````

Renders into the following, which is indeed ordered by descending total time.

![image](https://user-images.githubusercontent.com/23149353/162157590-f06b132e-be65-4959-b621-2ff21cb573f5.png)

If this doesn't work for you, can you please post the query you are using + screenshot of the resulting rendered block? Feel free to blur any personal information in that.

In the meantime, I would like to refer you to the project documentation: https://github.com/mcndt/obsidian-toggl-integration/wiki/Toggl-Query-Language-(TQL)-Reference

**Comment by mmfs37** [comment]
idk what I tried when writing this question. Probably sort Time desc or somthing. Now tried it with your format and everything works. Thank you very much
