### ISSUE TITLE
What does it mean when it says "toggl-client running in legacy mode."?

### ISSUE THREAD

**Issue by GitMurf** [mcndt/obsidian-toggl-integration#90]
What does it mean when it says "toggl-client running in legacy mode."? Is this expected?

Thanks!

**Comment by mcndt** [comment]
Hi GitMurf,

A few months ago I forked the [toggl-client](https://github.com/saintedlama/toggl-client) library I depend on to use Obsidian's built-in API for making web requests. I did this so that the plugin is one step closer to supporting mobile (though I currently have no near-future plans to support this).

Using the Obsidian API for web requests requires Obsidian 0.13.25 to be installed. If you are running an older version of the Obsidian client, you get this alert and the Toggl client falls back to the original implementation of the library. 

Note that this does not affect the use of the plugin in the slightest. Perhaps I should have worded the console message a bit better.

Hope that clears things up for you!

**Comment by GitMurf** [comment]
Hi @mcndt thanks for clarifying. I am on the very recent version of Obsidian though. I have auto update on so always am on the most recent version. Thoughts?

**Comment by mcndt** [comment]
One thing I can think of is that your installer version is quite old. Sometimes the Obsidian team advises to redownload Obsidian to get all the latest changes. 

You can just download the app again on the website and install it, it won't affect your settings or notes.
